// 90개 도시 영어 이름 + 한 줄 설명 (EN 모드용). DETAILS.en 없을 때 폴백으로 사용.
var EN_CITY = {
"강릉":{n:"Gangneung",c:"A serpent from Heo Gyun's tale becomes a dragon guarding Gangneung"},
"서울":{n:"Seoul",c:"By night at Gwanghwamun, Hangeul letters bloom into light over the old capital"},
"수원":{n:"Suwon",c:"King Jeongjo's devotion and Hwaseong's torchlight circle the fortress walls"},
"담양":{n:"Damyang",c:"Bamboo-grove wind reborn as Song Sun and Jeong Cheol's gasa poetry, in light"},
"안동":{n:"Andong",c:"Sleeping Hahoe masks wake for a Byeolsingut rite under the moon"},
"경주":{n:"Gyeongju",c:"Thousand-year Silla wakes in starlight; a guardian dragon-king protects the East Sea"},
"전주":{n:"Jeonju",c:"Pansori melodies surge over hanok tiles as the Joseon dynasty begins"},
"부여":{n:"Buyeo",c:"The great Baekje incense burner's smoke rises as the soul of Baekje"},
"남원":{n:"Namwon",c:"A spring night at Gwanghallu; Chunhyang's love crosses Ojak Bridge in light"},
"통영":{n:"Tongyeong",c:"Yun Isang's music meets Admiral Yi's crane-wing formation over the sea"},
"진주":{n:"Jinju",c:"Among Namgang lantern lights, Nongae's loyalty blazes across the river"},
"강진":{n:"Gangjin",c:"In exile's night, Dasan's brush and celadon blue-green become stars of Silhak"},
"제주":{n:"Jeju",c:"Grandmother Seolmundae rises from the sea to shape Jeju — a light of creation"},
"순천":{n:"Suncheon",c:"Im Gyeong-eop's one-night fortress wager, and Suncheon Bay's reeds"},
"여수":{n:"Yeosu",c:"Home of the turtle ship — built at Seonso and launched into the night sea"},
"진도":{n:"Jindo",c:"Grandma Ppong's parting sea and the Myeongnyang tidal strait"},
"영광":{n:"Yeonggwang",c:"Marananta's Indian Buddhism first lands at Beopseongpo — Buddhism enters Baekje"},
"화순":{n:"Hwasun",c:"Unjusa's thousand Buddhas and pagodas, and the unfinished reclining Buddha"},
"목포":{n:"Mokpo",c:"Yi Sun-sin's straw-stack ruse at Nojeokbong, and a modern port's double history"},
"해남":{n:"Haenam",c:"Gosan Yun Seon-do's Nogudang — four seasons of fisherman's songs, and blue rain"},
"나주":{n:"Naju",c:"Queen Janghwa and the Yeongsan River — a river that births a dynasty"},
"곡성":{n:"Gokseong",c:"The origin of Sim Cheong (Won Hong-jang) and sight restored by the Seomjin River"},
"완도":{n:"Wando",c:"Jang Bogo's Cheonghaejin — three kingdoms' ships meet on one island"},
"보성":{n:"Boseong",c:"A 1,600-year tea town; sea fog nurtures terraced green-tea fields"},
"김해":{n:"Gimhae",c:"King Suro and Heo Hwang-ok's iron kingdom, Geumgwan Gaya"},
"합천":{n:"Hapcheon",c:"The Tripitaka Koreana — 80,000 prayers carved in wood become a river of light"},
"밀양":{n:"Miryang",c:"Under Yeongnamnu's moonlight, Arang's wronged spirit finds release"},
"남해":{n:"Namhae",c:"Yi Sun-sin's last star at Noryang, and life on 100 terraced rice steps"},
"하동":{n:"Hadong",c:"Park Kyong-ni's 'Land' at Pyeongsa-ri — a field written by the river, held by Jirisan"},
"창녕":{n:"Changnyeong",c:"Bihwa Gaya's buried girl Song-hyeon breathes again in Upo Wetland's mist"},
"산청":{n:"Sancheong",c:"Heo Jun's Donguibogam — medicine mapping the body as a universe of light"},
"함양":{n:"Hamyang",c:"Choe Chi-won turned a river to plant Sangnim, a thousand-year forest"},
"서귀포(대정)":{n:"Seogwipo (Daejeong)",c:"Chusa's exile — the pine of Sehando, greener the colder it grows"},
"서귀포(성산)":{n:"Seogwipo (Seongsan)",c:"Haenyeo divers work the sea beneath Seongsan Ilchulbong, born of eruption"},
"청주":{n:"Cheongju",c:"Jikji — molten iron cast into letters, letters becoming light (oldest metal type)"},
"충주":{n:"Chungju",c:"Fallen Gaya's musician Ureuk plays the gayageum on Tangeumdae's cliff"},
"단양":{n:"Danyang",c:"On Dodam Sambong afloat the river, young Jeong Do-jeon drafts a new nation"},
"제천":{n:"Jecheon",c:"A musician dams the water, making Uirimji — unfailing for 1,500 years"},
"공주":{n:"Gongju",c:"As King Muryeong's sealed stone door opens, Baekje's light pours out"},
"서산":{n:"Seosan",c:"When the sun moves, the rock-carved Baekje Triad (the Baekje Smile) smiles too"},
"논산":{n:"Nonsan",c:"In troubled times, the giant Eunjin Maitreya rises as the people look up"},
"예산":{n:"Yesan",c:"Chusa's single brush goes beyond calligraphy to become the Sehando painting"},
"홍성":{n:"Hongseong",c:"Choe Yeong, Kim Jwa-jin, Han Yong-un, Yi Eung-no — one town's lineage of spirit"},
"아산":{n:"Asan",c:"The line drawn by Admiral Yi's bowstring becomes a chart of the sea"},
"태안":{n:"Taean",c:"A coastal rock-carved Buddha Triad that guarded ships setting out to sea"},
"보령":{n:"Boryeong",c:"Nampo inkstones once ground, and mudflats that cover the body — clay transformed"},
"춘천":{n:"Chuncheon",c:"Cheongpyeongsa's lovesick serpent, its obsession freed by lightning into nirvana"},
"원주":{n:"Wonju",c:"The bell-toll of the pheasant that repaid a kindness on Chiaksan"},
"속초":{n:"Sokcho",c:"Abai Village's ferry — longing for a North one can never return to"},
"평창":{n:"Pyeongchang",c:"Odaesan's Jeokmyeolbogung — the Buddha in an altar's empty seat, no statue"},
"정선":{n:"Jeongseon",c:"The sorrow of the Auraji maiden and youth becomes the Jeongseon Arirang"},
"영월":{n:"Yeongwol",c:"King Danjong's exile at Cheongnyeongpo and the cry of the scops owl"},
"삼척":{n:"Samcheok",c:"Heo Mok's East Sea stele — a spell that ruled the sea with letters"},
"철원":{n:"Cheorwon",c:"Gung-ye's Taebong capital — a Maitreya's city halted in the DMZ"},
"양양":{n:"Yangyang",c:"Uisang's Hongnyeonam at Naksansa — Avalokitesvara in the red lotus, led by a bluebird"},
"인제":{n:"Inje",c:"Manhae Han Yong-un writes 'The Silence of the Beloved' at Baekdamsa"},
"태백":{n:"Taebaek",c:"The Hwangji Pond janjamot legend and the source of the Nakdong River"},
"영주":{n:"Yeongju",c:"Uisang and Seonmyo — love becomes a dragon, then a floating stone guarding Muryangsujeon"},
"고령":{n:"Goryeong",c:"Ureuk's 12-string gayageum and Jisan-dong burials — a vanished Gaya's last song"},
"포항":{n:"Pohang",c:"Yeono-rang and Seo-nyeo — when sun and moon depart, a bolt of silk brings the sun back"},
"군위":{n:"Gunwi",c:"Iryeon writes the Samguk Yusa — from his brush, Dangun and myths come alive"},
"문경":{n:"Mungyeong",c:"At Saejae, a white-robed scholar and a coal-dusted modern miner cross paths"},
"울진":{n:"Uljin",c:"Seongnyu Cave's Silla hwarang and monk inscriptions revive in light"},
"청송":{n:"Cheongsong",c:"The Juwang legend — a fugitive's last day within volcanic folding-screen cliffs"},
"영덕":{n:"Yeongdeok",c:"Righteous-army leader Shin Dol-seok, the Taebaek tiger, racing between mountain and sea"},
"영천":{n:"Yeongcheon",c:"Geojoam's 500 arhats — a forest of faces, each with a different expression"},
"상주":{n:"Sangju",c:"The town that named Gyeongsang and the Nakdong; white of rice, persimmon and silkworm"},
"울릉도":{n:"Ulleungdo",c:"Usanguk's King Uhae's sea kingdom — a mysterious independent land at the sea's edge"},
"독도":{n:"Dokdo",c:"The East Sea's end, a rocky isle where sea lions played — the light of a land we've kept"},
"고양":{n:"Goyang",c:"Gwon Yul's Haengju victory — nameless hands carrying stones in their skirts"},
"용인":{n:"Yongin",c:"Jeong Mong-ju's Dansimga — where the wind-blown funeral banner came to rest"},
"파주":{n:"Paju",c:"Yulgok Yi I's Hwaseokjeong — a scholar's pavilion lighting the king's flight"},
"강화":{n:"Ganghwa",c:"Dangun's Chamseongdan and dolmens — an altar joining heaven (circle) and earth (square)"},
"남양주":{n:"Namyangju",c:"Dasan Jeong Yak-yong's geojunggi — thought becoming a machine that lifts stone"},
"여주":{n:"Yeoju",c:"Sejong's Yeongneung and Silleuksa — the king who put the people's speech into letters"},
"광주(경기)":{n:"Gwangju (Gyeonggi)",c:"Namhansanseong — walls that held 47 days and the gate that finally opened"},
"안성":{n:"Anseong",c:"Baudeogi — a wandering girl who became the finest tightrope performer"},
"인천":{n:"Incheon",c:"Jemulpo's opening and Chinatown — where a foreign dish became the nation's food"},
"양주":{n:"Yangju",c:"Hoeamsa site and Master Hyegeun — a 262-room temple where a king stayed with his teacher"},
"이천":{n:"Icheon",c:"Ceramic wood-fired kilns — clay eating fire to become vessels of centuries"},
"김포":{n:"Gimpo",c:"The ferryman Sondol — a beheaded boatman who saved the one sea route (the Sondol wind)"},
"군산":{n:"Gunsan",c:"Floating piers and Jjaebo wharf — memory of stolen rice and river (Chae Man-sik)"},
"김제":{n:"Gimje",c:"Byeokgolje's dragons and maiden Danya — sacrifice from paddy water and Maitreya's promise"},
"고창":{n:"Gochang",c:"The silence of dolmens and Shin Jae-hyo's pansori — stone begins to sing"},
"부안":{n:"Buan",c:"Chaeseokgang's strata and Yi Mae-chang — pages of longing left unwritten"},
"정읍":{n:"Jeongeup",c:"Jeongeupsa, the only surviving Baekje song — moonlight lighting a husband's way home"},
"익산":{n:"Iksan",c:"Mireuksa site and Lady Sataek-jeokdeok — a queen whose truth in the pagoda rewrote legend"},
"무주":{n:"Muju",c:"Fireflies — the smallest light, seen only when the dark deepens"},
"임실":{n:"Imsil",c:"Pilbong nongak and Imsil cheese — rhythm binding separate people into one breath"},
"진안":{n:"Jinan",c:"Maisan's stone pagodas — one person's universe, stacked bare-handed, unfallen 100 years"}
};
